### ISSUE TITLE
Update Docker image

### ISSUE THREAD

**Issue by vpkopylov** [cachapa/tudo_server#5]
I just  tried to run the server and encountered a few issues:
1. Readme  instructs to run  `pub get`  but there is no such command in flutter sdk (I am on Arch Linux, sdk version 3.16.5), maybe it should be `flutter pub get`?
2.  There is docker-compose.yml  file in this repo, but it is not described in readme, although it would be convenient just to run `docker-compose up` instead of  manually installing and configuring postgres and tudo server
3. `docker-compose up` is not working out of box, because it uses tudo_server image v35 that does not exists any more, maybe we would be better off using the most recent stable versions of postgres and tudo server instead (i.e. latest)?

**Comment by cachapa** [comment]
Thanks for the notice, the Dart SDK moved the `pub` command inside the `dart` executable, so it's now `dart pub …`. I updated the Readme.

Regarding Docker, that code was contributed by another user.
I'm not very proficient with Docker and don't currently have the time to look into that, so I'd appreciate it if someone else could contribute the fix.

In any case I'll change the title of this issue to reflect that.

**Comment by bo0tzz** [comment]
The docker-compose.yml should just work if you update the tag to the new version (found at https://github.com/cachapa/tudo_server/pkgs/container/tudo_server) or use `release`. It seems like new versions of the docker image are not quite released automatically, as that is triggered from a deploy workflow (https://github.com/cachapa/tudo_server/blob/master/.github/workflows/deploy.yml) that is manually started.

**Comment by vpkopylov** [comment]
@cachapa Thanks!
@bo0tzz I've managed to get docker-compose working by manually changing the tag.  The point is that if we commit a tag for the most recent version (`release` as you mentioned) it would be more robust and wouldn't require manual actions

**Comment by bo0tzz** [comment]
I understand that perspective. My personal opinion on this sort of thing is usually that
1. Rolling tags like `release` are a bad idea as you can't be sure what version you're actually deploying
2. The compose file supplied by a repository is a starting point for people to copy over to their own setup and manage there, which would include updating the tag when new versions come out.

That said, if @cachapa prefers I'm happy to do it this way, of course :)

**Comment by vpkopylov** [comment]
@bo0tzz 
1. Completely agree, I do not use such tags in production environment, especially for the software where breaking changes are expected. 
2. I thought  that `docker-compose.yml` in this repo is mostly supposed for experiments with the client. And the most important thing that this repo is indeed always the most recent version of the software, seems reasonable for me that `docker-compose` config reflects this. What do you think about putting  a comment with a hint to change the tag for a specific version for using in a prod environment?

**Comment by cachapa** [comment]
> Rolling tags like release are a bad idea as you can't be sure what version you're actually deploying

I switched back to manual tagging and releasing from the master branch as I found using the release branch to trigger releases a bit unwieldy for this project.

Master usually represents the production state anyway and there's no real need to complicate things further for such a small project.

@bo0tzz WDYT, and would you be willing to update the script to reflect these changes?

Also, if you have the time, I would appreciate it if you could also write a couple of lines in the readme: #6.

**Comment by vpkopylov** [comment]
btw, I believe that  postgres should be backward compatible at least for minor versions, so we can use a more general tag for postgres and still avoid breaking changes, i.e v14
Another thing that I would consider is  only putting dependencies in compose (so postgres), probably using same defaults for the settings as for `todo_server`. This way one can use the most recent `todo_server` version from the repo itself and avoid dealing with dependencies setup. Maybe creating two files would be the optimal solution, one for production use and another for running the repo sources.

**Comment by bo0tzz** [comment]
> WDYT, and would you be willing to update the script to reflect these changes?

Setting up the docker build to just track the master branch is pretty straightforward, but of course it does mean that there are no longer `v46` etc tags. That's not a problem though. I'll try to PR that and #6 this weekend.

**Comment by cachapa** [comment]
I meant tracking release tags such as v46 in the master branch

**Comment by bo0tzz** [comment]
That works. I see you created github release `v47` manually. Is that the plan from now on? Should I change the docker workflow to be triggered by releases instead of by the `deploy` workflow?

**Comment by cachapa** [comment]
Yeah, sorry for the change, I just realised I made it when I was updating the workflows in other projects and forgot that this one had the docker job.

**Comment by bo0tzz** [comment]
No problem, should be easy to change.
